### ISSUE TITLE
update header for branding

### ISSUE THREAD

**Issue by sandikbarr** [PRX/styleguide.prx.org#109]
![desktop](https://user-images.githubusercontent.com/2250413/40672702-31204e9c-6335-11e8-9880-5d90e8f0d0e1.png)

* [x] The header should have a dark background-color ~`#1a1a1a`~ -it says to use `#1a1a1a` on corporate branding but is actually using `#1c1c1c`
* [x] The username moves to the user apps menu
* [x] The user image has a 20px(?) right padding rather than the 100px plus gutter space it has now
* [x] The logo has 20px(?) left padding rather than the 100px plus gutter it has now
* [x] The logo itself is how tall? -vertical padding is included in the image itself
* [x] The header including padding is how tall? -left the same height

**Comment by sandikbarr** [comment]
It looks like the top and bottom padding are a bit tighter than we currently have. I thought we had a style guide on this floating around somewhere but I can't find it. @farski?

**Comment by sandikbarr** [comment]
Would it be better if our logo and user image were aligned with the content rather than pushed to the edges in all cases?  On corporate, the logo is left aligned to the content. That content doesn't have aa much of a definite right line, so it makes sense to push to the edge. On Publish, the content the header was designed for, the logo and user image are left and right aligned to the content. On Metrics, we're just using the style guide header that was designed for content in publish with a lot more left right padding, so they are not aligned to anything. (I am also assuming that we are only dropping the gutters for Metrics, so that's another thing to consider with logo and user image placement aligned to content.)

**Comment by farski** [comment]
That work I was doing in Sketch was just for mockup purposes, so definitely not pixel-perfect. That spacing recommendation in the PRX style guide probably is more room than we need in the header, though. I haven't had a chance to think too much about how this style would work/differ for various apps.
