### ISSUE TITLE
Add a new sticky header component

### ISSUE THREAD

**Issue by brandonhundt** [PRX/styleguide.prx.org#132]
The idea is that this will replace the current status bar implementation, but will allow us to take a more iterative approach. 

![screen shot 2019-03-01 at 2 16 32 pm](https://user-images.githubusercontent.com/369739/53663844-732bf900-3c2c-11e9-8c07-28f57aaba604.png)

Notes: 
- Back button goes to the Publish homepage
- The title space will vary on screen width.
- Link the logo to the to the series page

See the following screenshots for how this should look:
![episode - bottom scheduled](https://user-images.githubusercontent.com/369739/53663913-a4a4c480-3c2c-11e9-80a2-092d8b31ece9.png)
![episode - published](https://user-images.githubusercontent.com/369739/53663914-a53d5b00-3c2c-11e9-95a6-c6f3a451e626.png)
![episode - scrolled draft](https://user-images.githubusercontent.com/369739/53663915-a53d5b00-3c2c-11e9-9e92-7c4a2c93f975.png)

**Comment by kookster** [comment]
looks like #172 took care of this.
