### ISSUE TITLE
design user menu

### ISSUE THREAD

**Issue by sandikbarr** [PRX/styleguide.prx.org#149]
design work for username.
* does this include logout?
* username, other user profile info
* link to edit user profile?

related: #112 user apps should display user name

**Comment by cavis** [comment]
Background: info available from `https://id.prx.org/userinfo?scope=profile%20apps` when logged in.  Currently we don't have a `GET logout` link in ID - just a `DELETE logout`.

**Comment by brandonhundt** [comment]
Closing. Covered in #298
