### ISSUE TITLE
design search component

### ISSUE THREAD

**Issue by sandikbarr** [PRX/styleguide.prx.org#151]
* does publish search still exist, as advanced search?
* metrics episode search?
* metrics podcast/show selector

**Comment by IcusFMagni** [comment]
Address already existent search in publish

**Comment by cavis** [comment]
I'm a bit conflicted if we should just be using CMS / ElasticSearch across the board or not.  It certainly has some advantages over Castle/Postgres searching.  I guess I'm leaning towards: ElasticSearch everything and standardize display, but delegate links to the host app (Metrics/Publish/etc).

**Comment by brandonhundt** [comment]
Closing. Covered in #298
