### ISSUE TITLE
Material compatible PRX base styles

### ISSUE THREAD

**Issue by cavis** [PRX/styleguide.prx.org#211]
We need some base styles/layouts for use in Material projects.  Including the slightly-different classes/structures in:

- https://material.angular.io
- https://materializecss.com

Also: [CSS reset](https://dev.to/hankchizljaw/a-modern-css-reset-6p3)

**Comment by kookster** [comment]
Looks like angular material is using `material-components-web`:
https://github.com/material-components/material-components-web

Is there a rails gem using that, or can we use it w/o a rails gem making it easier to include?
