### ISSUE TITLE
multiple select component

### ISSUE THREAD

**Issue by sandikbarr** [PRX/styleguide.prx.org#54]
Add a dropdown multiple select component. Component should allow selection of multiple options, type/search to filter selections, and the ability to clear selected options.

Note: We had a need for this in Publish at one point, but seem to have moved past it: https://github.com/PRX/publish.prx.org/issues/283

**Comment by cavis** [comment]
Whoops - i stole your ticket!  Implemented in #55 (for PRX/publish.prx.org#449).  Though we should probably open some more tickets to address accessibility, and other bugs mentioned in there.  Some of those tickets exist in the parent repo, in fact.

**Comment by sandikbarr** [comment]
@cavis that's cool. I'm too slow.
