### ISSUE TITLE
Filter selected options for prx-select

### ISSUE THREAD

**Issue by cavis** [PRX/styleguide.prx.org#58]
Pretty sure the underlying lib doesn't handle this.  Should test for that, but otherwise:

- [x] Filter incoming `[selected]` to remove values not available in the options.
- [x] Log a warning when removing these values
- [ ] Check for `._single` when setting the selected, instead of checking if it's an array.  (Maybe the val is an array-of-arrays?)

**Comment by pkarman** [comment]
@cavis can you give this a Priority and Estimate?

**Comment by cavis** [comment]
yep

**Comment by pstjean** [comment]
> Check for ._single when setting the selected, instead of checking if it's an array. (Maybe the val is an array-of-arrays?)

Not needed with `ng-select` as `selected` is an array of the selected values when `._single` is false and simply the selected value when `._single` is true.

**Comment by pstjean** [comment]
Addressed in #127
