### ISSUE TITLE
active link color lacking contrast

### ISSUE THREAD

**Issue by sandikbarr** [PRX/styleguide.prx.org#83]
The active/selected link color doesn't have enough contrast from the regular link color to distinguish it from regular links. In the example, the active/selected link is page 1.
<img width="338" alt="screen shot 2018-01-05 at 3 48 42 pm" src="https://user-images.githubusercontent.com/2250413/34630020-f71b0744-f22f-11e7-942a-b145763df71e.png">

**Comment by pkarman** [comment]
@farski making this "high" since it impacts UX. Please give it some design love.

**Comment by farski** [comment]
Let's just do an underline for now. Bold, padding+background, etc all change the horizontal sizing. We can readdress this more thoroughly after beta.

**Comment by sandikbarr** [comment]
@pkarman since the decision is to just change this for metrics, can we keep this ticket open for the styleguide, bump it from the sprint, and add a new metrics ticket to the sprint to underline the current page number?

**Comment by sandikbarr** [comment]
More feedback on the active link color during bug bash https://github.com/PRX/metrics.prx.org/issues/227

**Comment by pkarman** [comment]
As a point of reference, https://www.w3schools.com/css/css3_pagination.asp

I personally like the Bordered Pagination style. Very clear and sharp.

**Comment by pkarman** [comment]
![screen shot 2018-02-13 at 4 26 30 pm](https://user-images.githubusercontent.com/1205061/36177241-afbb4d18-10da-11e8-8ac1-6f6d0229bb70.png)

@sandikbarr @farski what do you think of this style?

**Comment by sandikbarr** [comment]
I like it. Those buttons are gonna be much nicer for my clumsy clicking.

Any reason we would also want to tell them how many pages there are? If so, I can help with making that information available to the paging component.

**Comment by pkarman** [comment]
bigger snap:
![screen shot 2018-02-13 at 4 30 27 pm](https://user-images.githubusercontent.com/1205061/36177447-3f223ade-10db-11e8-8338-e653175cdcf1.png)

**Comment by pkarman** [comment]
I have `totalPages` available to me already, so I have added that as the final button with a `title` attribute for hover. We can use the page number instead of the `>>|` is we think that is more clear.
